export const GET_TOP_HEADLINES = 'GET_TOP_HEADLINES';
export const GET_TOP_HEADLINES_ERR = 'GET_TOP_HEADLINES_ERR';
export const GET_TOP_HEADLINES_BY_CATEGORY = 'GET_TOP_HEADLINES_BY_CATEGORY';
export const GET_TOP_HEADLINES_BY_CATEGORY_ERR = 'GET_TOP_HEADLINES_BY_CATEGORY_ERR';
export const GET_HEADLINES_BY_SEARCH_TERM = 'GET_HEADLINES_BY_SEARCH_TERM';
export const GET_HEADLINES_BY_SEARCH_TERM_ERR = 'GET_HEADLINES_BY_SEARCH_TERM_ERR';
